### ISSUE TITLE
Test and Predictions sizes are different

### ISSUE THREAD

**Issue by ASoleimaniB** [UKPLab/fever-2018-team-athene#3]
Fever Test Set has 19998 samples but final predictions (predictions.jsonl) makes 19950 predictions!
Is this a bug for the code or something else?

**Comment by littsler** [comment]
That is because sometimes the sentence retrieval model cannot predict any evidence for some cases. According to the problem setting of FEVER, these cases should be directly labeled as Not Enough Info in the claim validation. So we filtered out the cases with no predicted evidence during the claim validation. We will update the end-to-end pipeline later to include the post-processing for these cases.

**Comment by littsler** [comment]
Hi @ASoleimaniB ,

The pipeline is updated. The post-processing is now included.

**Comment by hanselowski** [comment]
We consider the issue to be closed
