### ISSUE TITLE
Syntax error in your latest code

### ISSUE THREAD

**Issue by drfeversharedtask** [UKPLab/fever-2018-team-athene#5]
When I run the following file:
PYTHONPATH=src python ./src/scripts/athene/pipeline.py

I get the following error:
 File "./src/scripts/athene/pipeline.py", line 100
    def sentence_retrieval_ensemble(logger, mode: Mode = Mode.PIPELINE):
                                                ^
SyntaxError: invalid syntax

**Comment by littsler** [comment]
Hi @drfeversharedtask I cannot reproduce this error. Could you please confirm the python environment?

**Comment by drfeversharedtask** [comment]
Have you checked on your end whether on a clean machine you were able to run the end-to-end pipeline of the submitted models following your guidlines?

**Comment by littsler** [comment]
Hi @drfeversharedtask This is a bug. The word vocabulary did not reserve one extra slot for the PADDING. And I notice that you are using CPU. By using GPU no error will be thrown due to the different behavior of tensorflow-gpu. That is why we have not encountered this error.
[https://github.com/tensorflow/tensorflow/issues/5847](https://github.com/tensorflow/tensorflow/issues/5847)
I fixed the word embedding. Please let me know if there is any further problem. Thx.
